version: "3.6"

services:
  chrome:
    image: selenium/standalone-chrome:latest
    hostname: chrome
    privileged: true
    shm_size: 2g
    ports:
      - "4444:4444"
    restart: unless-stopped

  filmweb_watchdog:
    depends_on:
      - chrome
    container_name: filmweb_watchdog
    image: filmweb_watchdog
    volumes:
      - type: bind
        source: ./data
        target: /data
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DOCKER_CONTAINER=True
      - LOG_LEVEL=20
    restart: unless-stopped 

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 600 filmweb_watchdog
    restart: unless-stopped
