version: "3.6"

services:
  headless_chrome:
    image: browserless/chrome:latest
    ports:
      - "3000:3000"
    container_name: headless_chrome
    environment:
      - DEBUG=-*

  filmweb_watchdog:
    depends_on:
      - headless_chrome
    container_name: filmweb_watchdog
    image: filmweb_watchdog
    volumes:
      - type: bind
        source: ./data
        target: /data
    build:
      context: .
      dockerfile: Dockerfile
