version: "3.6"

services:
  chrome:
    image: selenium/standalone-chrome:latest
    hostname: chrome
    privileged: true
    shm_size: 2g
    ports:
      - "4444:4444"
    restart: unless-stopped

  filmweb_watchdog:
    depends_on:
      - chrome
    container_name: filmweb_watchdog
    image: filmweb_watchdog
    volumes:
      - type: bind
        source: ./data
        target: /data
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DOCKER_CONTAINER=True
    restart: unless-stopped

  restarter:
    image: docker:cli
    volumes: ["/var/run/docker.sock:/var/run/docker.sock"]
    command: ["/bin/sh", "-c", "while true; do sleep 43200; docker restart filmweb_watchdog; done"]
    restart: unless-stopped
